import { BRAND } from "@/config/brand";
import {
  formatMoney,
  formatTime12h,
  formatTripDate,
  oneLineNote,
} from "@/lib/format";
import { Itinerary } from "@/types/itinerary";
import { TripPlan } from "@/types/trip-plan";

export type ItineraryExportContext = {
  itinerary: Itinerary;
  plan?: Pick<TripPlan, "adults" | "children" | "startDate" | "endDate">;
};

/** Cover date line like "July 8–14" (same year) or full range when years differ. */
export function formatCoverDateRange(startIso: string, endIso: string): string {
  if (!startIso || !endIso) return "";
  const start = new Date(`${startIso}T12:00:00`);
  const end = new Date(`${endIso}T12:00:00`);
  if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) return "";
  if (startIso === endIso) {
    return start.toLocaleDateString("en-US", { month: "long", day: "numeric" });
  }
  const sameYear = start.getFullYear() === end.getFullYear();
  const sameMonth = sameYear && start.getMonth() === end.getMonth();
  const startLabel = start.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    ...(sameYear ? {} : { year: "numeric" }),
  });
  if (sameMonth) {
    return `${startLabel}–${end.getDate()}`;
  }
  const endLabel = end.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    ...(sameYear ? {} : { year: "numeric" }),
  });
  return `${startLabel}–${endLabel}`;
}

export function formatFamilyCoverLines(
  plan: Pick<TripPlan, "adults" | "children"> | undefined,
): string[] {
  if (!plan) return [];
  const adults = `${plan.adults} Adult${plan.adults !== 1 ? "s" : ""}`;
  if (plan.children.length === 0) {
    return ["Family:", adults];
  }
  const ages = plan.children.join(" & ");
  return ["Family:", adults, `Kids: ${ages}`];
}

export function buildCoverContent(ctx: ItineraryExportContext): {
  destination: string;
  dateRange: string;
  familyLines: string[];
  generatedBy: string;
} {
  const { itinerary, plan } = ctx;
  const start = plan?.startDate ?? itinerary.days[0]?.date ?? "";
  const end = plan?.endDate ?? itinerary.days[itinerary.days.length - 1]?.date ?? start;
  return {
    destination: itinerary.destinationCity || itinerary.destination || "Your trip",
    dateRange: formatCoverDateRange(start, end) || itinerary.tripStartFormatted,
    familyLines: formatFamilyCoverLines(plan),
    generatedBy: `Generated by ${BRAND.name}`,
  };
}

/** Plain-text body for email share (no cover page needed). */
export function formatItineraryPlainText(ctx: ItineraryExportContext): string {
  const { itinerary } = ctx;
  const cover = buildCoverContent(ctx);
  const lines: string[] = [
    cover.destination,
    cover.dateRange,
    "",
    ...cover.familyLines,
    "",
    cover.generatedBy,
    "",
    "—".repeat(24),
    "",
  ];

  for (const day of itinerary.days) {
    lines.push(`Day ${day.day} — ${day.formattedDate || formatTripDate(day.date)}`);
    lines.push("");
    for (const a of day.activities) {
      const time = a.endTime
        ? `${formatTime12h(a.time)} – ${formatTime12h(a.endTime)}`
        : formatTime12h(a.time);
      lines.push(`${time}  ${a.title}`);
      if (a.location?.name) lines.push(`  📍 ${a.location.name}`);
      if (a.notes) lines.push(`  ${oneLineNote(a.notes, 120)}`);
    }
    const c = day.costBreakdown;
    lines.push("");
    lines.push(
      `Daily total: ${formatMoney(c.total, c.currency, itinerary.currencySymbol)}`,
    );
    lines.push("");
  }

  const tripTotal = itinerary.days.reduce((s, d) => s + d.costs.total, 0);
  lines.push(
    `Estimated trip total: ${formatMoney(tripTotal, itinerary.currency, itinerary.currencySymbol)}`,
  );
  return lines.join("\n").trim() + "\n";
}

export function itineraryPdfFilename(itinerary: Itinerary): string {
  const city = (itinerary.destinationCity || "trip")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  const start = itinerary.days[0]?.date ?? "trip";
  return `tripnestly-${city || "trip"}-${start}.pdf`;
}

export function isValidShareEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
}
