import { BRAND } from "@/config/brand";
import {
  formatMoney,
  formatPlaceRatingBadge,
  formatTime12h,
  formatTimeCompact,
  formatTripDate,
  oneLineNote,
} from "@/lib/format";
import { Itinerary, ItineraryActivity } from "@/types/itinerary";
import { TripPlan } from "@/types/trip-plan";

export type ItineraryExportContext = {
  itinerary: Itinerary;
  plan?: Pick<TripPlan, "adults" | "children" | "startDate" | "endDate">;
};

const TYPE_ICON: Record<ItineraryActivity["type"], string> = {
  meal: "🍽️",
  activity: "🎯",
  rest: "☕",
  nap: "😴",
  travel: "🚶",
};

function moneyWhole(amount: number, symbol: string): string {
  return `${symbol}${Math.round(amount).toLocaleString()}`;
}

/** Compact summary + expanded detail lines (same structure as the day-card UI). */
export function formatCompactActivityLines(
  activity: ItineraryActivity,
  currencySymbol: string,
  opts: { asciiStar?: boolean } = {},
): { summary: string; details: string[] } {
  const icon = TYPE_ICON[activity.type] ?? "";
  const badge = formatPlaceRatingBadge(activity.rating, activity.reviewCount);
  const badgeText =
    badge && opts.asciiStar ? badge.replace(/^★/, "*") : badge;
  const paid =
    activity.activityCost != null && activity.activityCost > 0
      ? moneyWhole(activity.activityCost, currencySymbol)
      : "";

  const summaryParts = [
    formatTimeCompact(activity.time),
    icon,
    activity.title,
    badgeText,
    paid,
  ].filter(Boolean);
  const summary = summaryParts.join("  ");

  const details: string[] = [];
  if (activity.endTime) {
    details.push(`${formatTime12h(activity.time)} – ${formatTime12h(activity.endTime)}`);
  }
  if (activity.location?.name) {
    // Prefer place name / place id over raw coordinates (coords can land on the wrong building).
    if (activity.placeId) {
      details.push(
        `Maps: https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(activity.location.name)}&query_place_id=${encodeURIComponent(activity.placeId)}`,
      );
    } else if (!/\barea\b/i.test(activity.location.name)) {
      details.push(
        `Maps: https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(activity.location.name)}`,
      );
    } else if (
      Number.isFinite(activity.location.lat) &&
      Number.isFinite(activity.location.lng)
    ) {
      details.push(
        `Maps: https://www.google.com/maps/search/?api=1&query=${activity.location.lat},${activity.location.lng}`,
      );
    }
  }
  if (activity.notes) {
    const note = oneLineNote(activity.notes, 140);
    if (note && !/^Day\s+\d+\s+[—–-]/i.test(note.trim())) {
      details.push(note);
    }
  }
  return { summary, details };
}

/** Cover date line like "July 8–14" (same year) or full range when years differ. */
export function formatCoverDateRange(startIso: string, endIso: string): string {
  if (!startIso || !endIso) return "";
  const start = new Date(`${startIso}T12:00:00`);
  const end = new Date(`${endIso}T12:00:00`);
  if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) return "";
  if (startIso === endIso) {
    return start.toLocaleDateString("en-US", { month: "long", day: "numeric" });
  }
  const sameYear = start.getFullYear() === end.getFullYear();
  const sameMonth = sameYear && start.getMonth() === end.getMonth();
  const startLabel = start.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    ...(sameYear ? {} : { year: "numeric" }),
  });
  if (sameMonth) {
    return `${startLabel}–${end.getDate()}`;
  }
  const endLabel = end.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    ...(sameYear ? {} : { year: "numeric" }),
  });
  return `${startLabel}–${endLabel}`;
}

export function formatFamilyCoverLines(
  plan: Pick<TripPlan, "adults" | "children"> | undefined,
): string[] {
  if (!plan) return [];
  const adults = `${plan.adults} Adult${plan.adults !== 1 ? "s" : ""}`;
  if (plan.children.length === 0) {
    return ["Family:", adults];
  }
  const ages = plan.children.join(" & ");
  return ["Family:", adults, `Kids: ${ages}`];
}

export function buildCoverContent(ctx: ItineraryExportContext): {
  destination: string;
  dateRange: string;
  familyLines: string[];
  generatedBy: string;
} {
  const { itinerary, plan } = ctx;
  const start = plan?.startDate ?? itinerary.days[0]?.date ?? "";
  const end = plan?.endDate ?? itinerary.days[itinerary.days.length - 1]?.date ?? start;
  return {
    destination: itinerary.destinationCity || itinerary.destination || "Your trip",
    dateRange: formatCoverDateRange(start, end) || itinerary.tripStartFormatted,
    familyLines: formatFamilyCoverLines(plan),
    generatedBy: `Generated by ${BRAND.name}`,
  };
}

/** Plain-text body for email share (no cover page needed). */
export function formatItineraryPlainText(ctx: ItineraryExportContext): string {
  const { itinerary } = ctx;
  const cover = buildCoverContent(ctx);
  const symbol = itinerary.currencySymbol;
  const lines: string[] = [
    cover.destination,
    cover.dateRange,
    "",
    ...cover.familyLines,
    "",
    cover.generatedBy,
    "",
    "—".repeat(24),
    "",
  ];

  for (const day of itinerary.days) {
    const c = day.costBreakdown;
    lines.push(
      day.displayTitle
        ? `Day ${day.day} · ${day.displayTitle} · ${day.formattedDate || formatTripDate(day.date)}  ${moneyWhole(c.total, symbol)}`
        : `Day ${day.day} · ${day.formattedDate || formatTripDate(day.date)}  ${moneyWhole(c.total, symbol)}`,
    );
    lines.push(
      `Food ${moneyWhole(c.food, symbol)}  ·  Transport ${moneyWhole(c.transport, symbol)}  ·  Activities ${moneyWhole(c.activities, symbol)}`,
    );
    lines.push("");
    for (const a of day.activities) {
      const { summary, details } = formatCompactActivityLines(a, symbol);
      lines.push(summary);
      for (const d of details) lines.push(`  ${d}`);
    }
    lines.push("");
  }

  const tripTotal = itinerary.days.reduce((s, d) => s + d.costs.total, 0);
  lines.push(
    `Estimated trip total: ${formatMoney(tripTotal, itinerary.currency, symbol)}`,
  );
  return lines.join("\n").trim() + "\n";
}

export function itineraryPdfFilename(itinerary: Itinerary): string {
  const city = (itinerary.destinationCity || "trip")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  const start = itinerary.days[0]?.date ?? "trip";
  return `tripnestly-${city || "trip"}-${start}.pdf`;
}

export function isValidShareEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
}
