import { LandmarkAgeTag } from "@/config/city-pricing";
import { BudgetStyle } from "@/types/trip-plan";

/** Meal slots that can map to a named restaurant. */
export type RestaurantMeal = "breakfast" | "lunch" | "dinner";

/** Dietary tags restaurants advertise support for (aligned with wizard quick picks). */
export type RestaurantDietary = "vegetarian" | "vegan" | "gluten-free" | "dairy-free";

export type CityRestaurant = {
  name: string;
  lat: number;
  lng: number;
  meals: RestaurantMeal[];
  ageTags: LandmarkAgeTag[];
  /** Strong dietary fit — preferred when the plan lists these needs. */
  dietary: RestaurantDietary[];
  /**
   * Weaker fit: the menu has options for these needs but the spot is not
   * primarily that diet. Used only after strong-fit places are exhausted.
   */
  dietaryOptions?: RestaurantDietary[];
  budgetStyles: BudgetStyle[];
  /** Short why-this-spot note shown on the itinerary. */
  familyNote: string;
};

/** Curated family-friendly restaurants keyed by city id (see city-pricing). */
export const CITY_RESTAURANTS: Record<string, CityRestaurant[]> = {
  "san-diego": [
    {
      name: "The Broken Yolk Cafe",
      lat: 32.747,
      lng: -117.1615,
      meals: ["breakfast"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Huge breakfast plates, high chairs, and a kids menu.",
    },
    {
      name: "Hash House A Go Go",
      lat: 32.7485,
      lng: -117.1608,
      meals: ["breakfast", "lunch"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Over-the-top portions — share plates work well for families.",
    },
    {
      name: "Breakfast Republic",
      lat: 32.7498,
      lng: -117.1495,
      meals: ["breakfast"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Neighborhood brunch with gluten-free and vegetarian plates.",
    },
    {
      name: "Snooze an A.M. Eatery",
      lat: 32.7115,
      lng: -117.1608,
      meals: ["breakfast"],
      ageTags: ["toddler", "child", "tween"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Pancake-focused brunch — high chairs and a kids menu.",
    },
    {
      name: "Lotus Cafe",
      lat: 32.7472,
      lng: -117.2505,
      meals: ["breakfast", "lunch"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegan", "vegetarian", "gluten-free"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Plant-based breakfast and lunch near the beaches.",
    },
    {
      name: "Plumeria Vegetarian Restaurant",
      lat: 32.7635,
      lng: -117.1295,
      meals: ["lunch", "dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegan", "vegetarian", "gluten-free"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Thai vegetarian/vegan kitchen with gluten-free curries.",
    },
    {
      name: "Evolution Fast Food",
      lat: 32.7488,
      lng: -117.1482,
      meals: ["lunch", "dinner"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegan", "vegetarian", "gluten-free"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Fast-casual vegan comfort food — easy with kids.",
    },
    {
      name: "Kindred",
      lat: 32.7482,
      lng: -117.1298,
      meals: ["dinner"],
      ageTags: ["tween", "teen"],
      dietary: ["vegan", "vegetarian"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Plant-based dinner with a lively family-friendly vibe.",
    },
    {
      name: "Oscar's Mexican Seafood",
      lat: 32.7492,
      lng: -117.2495,
      meals: ["lunch"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["gluten-free"],
      dietaryOptions: ["vegetarian"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Casual counter service — quick tacos near the beaches.",
    },
    {
      name: "Point Loma Seafoods",
      lat: 32.724,
      lng: -117.2245,
      meals: ["lunch"],
      ageTags: ["child", "tween", "teen"],
      dietary: [],
      dietaryOptions: ["gluten-free"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Harbor-side fish counter — easy outdoor seating with kids.",
    },
    {
      name: "Burger Lounge",
      lat: 32.7478,
      lng: -117.1602,
      meals: ["lunch", "dinner"],
      ageTags: ["toddler", "child", "tween"],
      dietary: ["gluten-free", "vegetarian"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Grass-fed burgers and a reliable kids menu.",
    },
    {
      name: "Native Foods Cafe",
      lat: 32.7675,
      lng: -117.1528,
      meals: ["lunch", "dinner"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegan", "vegetarian", "gluten-free"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Plant-based comfort food that works for vegan families.",
    },
    {
      name: "Cucina Urbana",
      lat: 32.7315,
      lng: -117.1472,
      meals: ["dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Lively Italian near Balboa Park — shareable plates for mixed ages.",
    },
    {
      name: "The Prado at Balboa Park",
      lat: 32.7312,
      lng: -117.1488,
      meals: ["lunch", "dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegetarian", "vegan", "gluten-free"],
      budgetStyles: ["splurge"],
      familyNote: "Garden setting with vegetarian and gluten-free options.",
    },
    {
      name: "Civico 1845",
      lat: 32.7218,
      lng: -117.1685,
      meals: ["dinner"],
      ageTags: ["tween", "teen"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Modern Italian in Little Italy — gluten-free pasta available.",
    },
    {
      name: "Truluck's",
      lat: 32.8705,
      lng: -117.2325,
      meals: ["dinner"],
      ageTags: ["teen"],
      dietary: ["gluten-free"],
      dietaryOptions: ["vegetarian"],
      budgetStyles: ["splurge"],
      familyNote: "Seafood dinner with gluten-free marked dishes.",
    },
  ],
  paris: [
    {
      name: "Café Kitsuné Tuileries",
      lat: 48.8635,
      lng: 2.3275,
      meals: ["breakfast"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Coffee and pastries steps from the Louvre gardens.",
    },
    {
      name: "Eric Kayser (Odéon)",
      lat: 48.8495,
      lng: 2.3395,
      meals: ["breakfast"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Bakery breakfast — grab croissants and sit nearby with little ones.",
    },
    {
      name: "Claus Paris",
      lat: 48.8572,
      lng: 2.3348,
      meals: ["breakfast"],
      ageTags: ["toddler", "child", "tween"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Quiet breakfast salon with gluten-free pastry options.",
    },
    {
      name: "Wild & the Moon",
      lat: 48.8602,
      lng: 2.3565,
      meals: ["breakfast", "lunch"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegan", "vegetarian", "gluten-free"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Fully plant-based café — smoothies and bowls for vegan families.",
    },
    {
      name: "Breizh Café Marais",
      lat: 48.8575,
      lng: 2.362,
      meals: ["lunch", "dinner"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Buckwheat galettes and cider — easy for kids and gluten-aware diners.",
    },
    {
      name: "Bouillon Chartier",
      lat: 48.8738,
      lng: 2.3435,
      meals: ["lunch", "dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: [],
      dietaryOptions: ["vegetarian", "gluten-free"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Classic Parisian bouillon — hearty plates without a big bill.",
    },
    {
      name: "Hank Burger",
      lat: 48.8638,
      lng: 2.3655,
      meals: ["lunch"],
      ageTags: ["toddler", "child", "tween"],
      dietary: ["vegetarian", "vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Veggie burgers in the Marais — fast and kid-friendly.",
    },
    {
      name: "Pink Mamma",
      lat: 48.8815,
      lng: 2.3385,
      meals: ["dinner"],
      ageTags: ["tween", "teen"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Buzzy Italian near Montmartre — pastas kids usually finish.",
    },
    {
      name: "Le Potager du Marais",
      lat: 48.8608,
      lng: 2.3555,
      meals: ["lunch", "dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegan", "vegetarian", "gluten-free"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Fully vegetarian/vegan kitchen with gluten-free options.",
    },
    {
      name: "East Mamma",
      lat: 48.8498,
      lng: 2.3795,
      meals: ["dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Family-style Italian — gluten-free pasta and kids portions.",
    },
  ],
  london: [
    {
      name: "The Breakfast Club (Soho)",
      lat: 51.5135,
      lng: -0.1365,
      meals: ["breakfast", "lunch"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "All-day brunch plates and a solid kids menu.",
    },
    {
      name: "Dishoom Covent Garden",
      lat: 51.5125,
      lng: -0.1235,
      meals: ["breakfast", "lunch", "dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegetarian", "vegan", "gluten-free"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Bombay café classics — naan and house black daal work for mixed diets.",
    },
    {
      name: "Wagamama (South Kensington)",
      lat: 51.4945,
      lng: -0.1745,
      meals: ["lunch", "dinner"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian", "vegan", "gluten-free"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Noodle bowls and a dedicated kids menu near the museums.",
    },
    {
      name: "PizzaExpress (Victoria)",
      lat: 51.4965,
      lng: -0.1435,
      meals: ["lunch", "dinner"],
      ageTags: ["toddler", "child", "tween"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Reliable pizza with gluten-free bases and dough balls for kids.",
    },
    {
      name: "Bill's (Covent Garden)",
      lat: 51.5118,
      lng: -0.1238,
      meals: ["breakfast", "lunch", "dinner"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced"],
      familyNote: "Relaxed British café — high chairs and familiar plates.",
    },
    {
      name: "Mildreds Soho",
      lat: 51.5132,
      lng: -0.1358,
      meals: ["lunch", "dinner"],
      ageTags: ["tween", "teen"],
      dietary: ["vegetarian", "vegan", "gluten-free"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Vegetarian institution with vegan and gluten-free mains.",
    },
  ],
  "tel-aviv": [
    {
      name: "Café Xoho",
      lat: 32.0805,
      lng: 34.7805,
      meals: ["breakfast"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian", "vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Neighborhood café breakfast with vegetarian and vegan options.",
    },
    {
      name: "Abu Hassan",
      lat: 32.0545,
      lng: 34.7515,
      meals: ["lunch"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegetarian", "vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Famous hummus — quick, filling, and naturally vegetarian.",
    },
    {
      name: "Port Said",
      lat: 32.0728,
      lng: 34.7802,
      meals: ["lunch", "dinner"],
      ageTags: ["tween", "teen"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan", "dairy-free"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Shared Middle Eastern plates near the beach hotels.",
    },
    {
      name: "Mizlala",
      lat: 32.0735,
      lng: 34.7815,
      meals: ["dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["gluten-free"],
      dietaryOptions: ["vegetarian", "dairy-free"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Modern Israeli cooking — shareable for families.",
    },
    {
      name: "Vitrina",
      lat: 32.0718,
      lng: 34.7825,
      meals: ["lunch", "dinner"],
      ageTags: ["toddler", "child", "tween"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan", "dairy-free"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Casual grill near Sarona — easy for younger kids.",
    },
  ],
  tokyo: [
    {
      name: "bills Omotesando",
      lat: 35.6655,
      lng: 139.7125,
      meals: ["breakfast", "lunch"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Famous ricotta hotcakes — relaxed brunch with kids.",
    },
    {
      name: "Kagurazaka Saryo",
      lat: 35.7005,
      lng: 139.7405,
      meals: ["breakfast"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Café breakfast near Kagurazaka — soft seating and quiet pace.",
    },
    {
      name: "Ichiran Shibuya",
      lat: 35.6598,
      lng: 139.7008,
      meals: ["lunch", "dinner"],
      ageTags: ["tween", "teen"],
      dietary: [],
      dietaryOptions: ["vegetarian"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Solo-booth ramen — fun for older kids who like noodles.",
    },
    {
      name: "Gonpachi Nishi-Azabu",
      lat: 35.6592,
      lng: 139.7235,
      meals: ["dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["gluten-free"],
      dietaryOptions: ["vegetarian"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Izakaya-style share plates — lively but workable with kids.",
    },
    {
      name: "Ain Soph. Journey",
      lat: 35.6685,
      lng: 139.7055,
      meals: ["lunch", "dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegan", "vegetarian"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Vegan café with colorful plates kids often try.",
    },
    {
      name: "Mos Burger (Ueno)",
      lat: 35.7125,
      lng: 139.7765,
      meals: ["lunch"],
      ageTags: ["toddler", "child", "tween"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save"],
      familyNote: "Familiar burgers near Ueno Park — fast with little ones.",
    },
  ],
  default: [
    {
      name: "Harbor Family Cafe",
      lat: 40.7135,
      lng: -74.0055,
      meals: ["breakfast"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Neighborhood breakfast spot with kids plates and high chairs.",
    },
    {
      name: "Market Street Diner",
      lat: 40.7145,
      lng: -74.007,
      meals: ["breakfast", "lunch"],
      ageTags: ["toddler", "child", "tween"],
      dietary: ["vegetarian"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Casual diner fare — quick turns for nap schedules.",
    },
    {
      name: "Sunrise Bowl Bar",
      lat: 40.7155,
      lng: -74.0045,
      meals: ["breakfast"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegan", "vegetarian", "gluten-free"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Plant-based breakfast bowls with gluten-free options.",
    },
    {
      name: "Parkside Pancake House",
      lat: 40.7118,
      lng: -74.0065,
      meals: ["breakfast", "lunch"],
      ageTags: ["toddler", "child", "tween"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Pancakes and high chairs — easy with little ones.",
    },
    {
      name: "Green Bowl Kitchen",
      lat: 40.715,
      lng: -74.004,
      meals: ["lunch", "dinner"],
      ageTags: ["child", "tween", "teen"],
      dietary: ["vegetarian", "vegan", "gluten-free"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Build-your-own bowls that cover most dietary needs.",
    },
    {
      name: "Corner Slice Pizzeria",
      lat: 40.712,
      lng: -74.008,
      meals: ["lunch", "dinner"],
      ageTags: ["toddler", "child", "tween"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Pizza and gluten-free crusts — always a safe family bet.",
    },
    {
      name: "The Lantern Table",
      lat: 40.716,
      lng: -74.0035,
      meals: ["dinner"],
      ageTags: ["tween", "teen"],
      dietary: ["vegetarian", "gluten-free"],
      dietaryOptions: ["vegan"],
      budgetStyles: ["balanced", "splurge"],
      familyNote: "Sit-down dinner with shareable plates for mixed ages.",
    },
    {
      name: "River Noodle House",
      lat: 40.7142,
      lng: -74.0028,
      meals: ["lunch", "dinner"],
      ageTags: ["toddler", "child", "tween", "teen"],
      dietary: ["vegetarian", "vegan", "gluten-free"],
      budgetStyles: ["save", "balanced"],
      familyNote: "Noodle bowls with vegan and gluten-free broths.",
    },
  ],
};

export function restaurantsForCityId(cityId: string): CityRestaurant[] {
  return CITY_RESTAURANTS[cityId] ?? CITY_RESTAURANTS.default;
}
